crea_qcmqcm_homepage:
    path:     /
    defaults: { _controller: CreaQCMQCMBundle:QCM:index }

crea_qcmqcm_list:
    path:     /liste
    defaults: { _controller: CreaQCMQCMBundle:QCM:list }

crea_qcmqcm_getAnswer:
    path:     /qcm/{id}
    defaults: { _controller: CreaQCMQCMBundle:QCM:answer }

crea_qcmqcm_generate:
    path:     /generer
    defaults: { _controller: CreaQCMQCMBundle:Generate:new }

crea_qcmqcm_postAnswer:
    path:     /answer/qcm/{id}
    defaults: { _controller: CreaQCMQCMBundle:Answer:post }